inspecode:

  experimental:
    runtime:
      python: 2

  ##----------------------------------------------------------------------------
  ## [on staging] SyntaxError -> abort
  ##----------------------------------------------------------------------------
  #autopep8:
  #  auto-fix: true
  #  thresholds: { num-issues: 444 }

  cpd:
    thresholds: { num-issues: 5 }

  flake8:
    options:
      --ignore:
      - E501    # 1844 issues
      - E261    #  848 issues
      - E302    #  797 issues
      - W503    #  371 issues
      - F401    #  248 issues
      - F841    #  171 issues
      - E231    #  164 issues
      - E305    #  148 issues
      - F821    #  138 issues
      - F811    #  108 issues
    thresholds: { num-issues: 870 }
      # 870 issues, when runtime python: 2
      # 787 issues, when runtime python: 3

  grep:
    thresholds: { num-issues: 10 }

  jscpd:
    thresholds: { num-issues: 17 }
      # 17 isseus on SaaS
      # 18 isseus on Errorprise

  misspell:
    auto-fix: true
    thresholds: { num-issues: 24 }

  nose2:
    thresholds: { num-issues: 22 }
      # 22 issues, when runtime python: 2
      # 20 issues, when runtime python: 3

  prospector:
    thresholds: { num-issues: 186 }
      # 186 issues on SaaS (runtime python: 2)
      # 106 isseus on SaaS (runtime python: 3)
      # 107 isseus on Errorprise (runtime python: 3)

  pycodestyle:
    options:
      --ignore:
      - E501    # 1861 issues
      - E261    #  848 issues
      - E302    #  797 issues
      - W503    #  371 issues
      - E231    #  164 issues
      - E305    #  148 issues
    thresholds: { num-issues: 645 }

  pyflakes:
    thresholds: { num-issues: 396 }
      # 396 issues, when runtime python: 2
      # 347 issues, when runtime python: 3

  ##----------------------------------------------------------------------------
  ## [runtime python: 2]
  ##  pylint requires Python '>=3.5.*' but the running Python is 2.7.16
  ##  cannot resolve dependencies
  ##
  ##  $ pylint --persistent=no --output-format=text --msg-template="${MSGTEMPLATE}" --py3k --jobs=1 ${INPUT}
  ##  RuntimeError: maximum recursion depth exceeded
  ##----------------------------------------------------------------------------
  ## [runtime python: 3]
  ##  $ pylint --persistent=no --output-format=text --msg-template="${MSGTEMPLATE}" --jobs=1 ${INPUT}
  ##  Traceback (most recent call last):
  ##    File "/opt/pyenv/versions/3.7.3/lib/python3.7/tokenize.py", line 397, in find_cookie
  ##      codec = lookup(encoding)
  ##  LookupError: unknown encoding: IBO-8859-1
  ##----------------------------------------------------------------------------
  #pylint:
  #  options:
  #    --py3k:
  #  thresholds: { num-issues: 242 }
  #    # 242 issues, when runtime python: 2
  #    # 347 issues, when runtime python: 3

  ##----------------------------------------------------------------------------
  ## [runtime python: 2]
  ##  pylint requires Python '>=3.5.*' but the running Python is 2.7.16
  ##  cannot resolve dependencies
  ##
  ##  ImportError while loading conftest '/home/rocro/src/github.com/tetrafolium/pylint/tests/conftest.py'.
  ##----------------------------------------------------------------------------
  #pytest:
  #  thresholds: { num-issues: 3 }

  ###------------------------------------------------
  ###  unused: <stdin>: hGetContents: invalid argument (invalid byte sequence)
  ###
  ###  Possibly Unused failed because the tags file had an invalid encoding.
  ###  Convert the tags file to UTF-8 and try again.
  ###------------------------------------------------
  #unused:
  #  thresholds: { num-issues: 999 }

  yapf:
    auto-fix: true
    thresholds: { num-issues: 493 }
      # 493 issues, when runtime python: 2
      # 486 issues, when runtime python: 3
